export const testIds = {
  catalogResult: 'catalog-result',
  exercisePickerResult: 'exercise-picker-result',
  routineCard: 'routine-card',
  sessionExercise: 'session-exercise',
  historySessionRow: 'history-session-row',
  progressWeightChart: 'progress-weight-chart',
  bodyMetricRow: 'body-metric-row',
} as const;

export const labels = {
  searchPlaceholder: 'Buscar ejercicio...',
  clearSearch: 'Limpiar',
  catalogHeading: 'Catálogo',
  instructionsHeading: 'Instrucciones',
  routinesHeading: 'Rutinas',
  addExerciseHeading: 'Agregar ejercicio',
  newRoutineNamePlaceholder: 'Nombre de la rutina',
  saveRoutine: 'Guardar rutina',
  createRoutine: 'Crear rutina',
  addExercise: 'Agregar',
  weightInputLabel: 'Peso (kg)',
  repsInputLabel: 'Reps',
  rpeInputLabel: 'RPE',
  historyHeading: 'Historial',
  progressHeading: 'Progreso',
  progressWeightLabel: 'Mejor peso por sesión',
  bodyMetricsHeading: 'Métricas corporales',
  bodyMetricDateLabel: 'Fecha y hora',
  bodyMetricWeightLabel: 'Peso (kg)',
  bodyMetricFatLabel: '% Grasa',
  bodyMetricWaistLabel: 'Cintura (cm)',
  newBodyMetric: 'Nueva',
  saveBodyMetric: 'Guardar',
} as const;
