server {
    listen 80;
    server_name _;

    location /exercises {
        alias /usr/share/nginx/html/exercises;
        autoindex off;
        add_header Accept-Ranges bytes always;
    }

    location / {
        return 404;
    }
}
